# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

hello_the_world:
    path: /hello-world
    controller: App\Controller\AdvertController::index


advert_index:
    path: /advert
    controller: App\Controller\AdvertController::index

advert_view:
    path: /advert/view/{id}
    controller: App\Controller\AdvertController::view

advert_add:
    path: /advert/add
    controller: App\Controller\AdvertController::add